/* Crate Capture: where to look. Each entry says what you can expect and how sure you can be of the licence.
   trust: 'high'  the site or collection is CC0 / public domain by design
          'check' the site has a CC0 or public-domain filter, but anyone can upload, so every item needs the checks
          'age'   public domain because of age (not a CC0 dedication): depends on the country, and on recording AND composition
          'make'  you make it
   Checked on 2026-10-05 against each site's own pages and documentation. Sites change: the checks in the guide matter more than this list. */
export const SOURCES = [
  { id: 'make', name: 'Make it yourself', trust: 'make', kind: 'Your own music', url: '',
    what: 'Music you write and record or synthesise yourself, then dedicate to CC0. The cleanest provenance there is.',
    how: 'Use your own synths and recordings. Do not use sample packs, loops or presets unless their licence allows CC0 redistribution (many do not: read it). Write down who played what. If anyone else played or wrote a part, get their agreement in writing before you dedicate it.',
    warn: 'CC0 cannot be taken back. Make sure every part is yours to give.' },
  { id: 'kenney', name: 'Kenney', trust: 'high', kind: 'Sound packs and jingles', url: 'https://kenney.nl/assets',
    what: 'Game assets by one creator, all CC0. Audio packs are mostly sound effects, with a Music Jingles pack.',
    how: 'Open Assets, filter to Audio, read the licence line on the pack page (it says CC0) and keep the licence text from the zip.',
    warn: 'Small and mostly effects, not full songs.' },
  { id: 'goldberg', name: 'Open Goldberg Variations', trust: 'high', kind: 'Classical piano recording', url: 'https://opengoldbergvariations.org/',
    what: 'A full studio recording of Bach\'s Goldberg Variations, and its score, released to the public domain with CC0 in 2012.',
    how: 'Download the recording from the project\'s own page. It is also mirrored on the Internet Archive, Musopen and others: take it from the project page and note the address.',
    warn: 'One work. Mirrors can carry wrong licence labels: use the project\'s own statement as the evidence.' },
  { id: 'oga', name: 'OpenGameArt', trust: 'check', kind: 'Game music and sounds', url: 'https://opengameart.org/',
    what: 'A large community library of game art and audio. You can limit a search to the Music type and the CC0 licence, and there are CC0 collections.',
    how: 'Browse > Art type: Music, License: CC0. On each page read the licence box, the credits, and then the text file inside the download.',
    warn: 'Anyone can upload. A real case: a pack labelled CC0 on its page had a text file inside saying CC BY 3.0. Trust the stricter one and log both.' },
  { id: 'freesound', name: 'Freesound', trust: 'check', kind: 'Loops, textures and sounds', url: 'https://freesound.org/',
    what: 'A huge community library of sounds and loops. Search results can be limited to Creative Commons 0.',
    how: 'Advanced search > License > Creative Commons 0. Or use the API with filter=license:"Creative Commons 0" (see the Tools tab). Keep the sound\'s page address and number.',
    warn: 'Freesound does not verify that uploaders own what they upload. Use "Flag it" on a page if a sound looks stolen.' },
  { id: 'openverse', name: 'Openverse', trust: 'check', kind: 'A search engine for open audio', url: 'https://openverse.org/search/audio',
    what: 'One search over open-licensed audio from several sources (currently Wikimedia Commons, Jamendo and Freesound), with licence filters including CC0 and Public Domain Mark.',
    how: 'Search audio, set the licence filter to CC0, then go to the original site from the result and do the checks there.',
    warn: 'It is a finder, not the source. The licence shown is what the original site said.' },
  { id: 'commons', name: 'Wikimedia Commons', trust: 'check', kind: 'Public domain and CC0 audio', url: 'https://commons.wikimedia.org/wiki/Commons:Free_media_resources/Music',
    what: 'A free media library with a page of music resources and many public domain and CC0 files. Every file page names its licence and its author.',
    how: 'Open the file page: read the licensing section and the "Original upload log". Prefer files with a clear author and source.',
    warn: 'Some are public domain only in certain countries. Read what it says about the country.' },
  { id: 'archive', name: 'Internet Archive', trust: 'check', kind: 'Everything, including netlabels and old records', url: 'https://archive.org/details/audio',
    what: 'The biggest collection of audio online: netlabel releases, old records, field recordings. Each item can carry a licence address.',
    how: 'Search with mediatype:audio and a licence address filter (see the Tools tab), or browse a netlabel. Read the item\'s licence line and its description.',
    warn: 'Uploaders add the licence themselves, and the same licence is written with different addresses. Many items have no licence at all: that is not CC0.' },
  { id: 'fma', name: 'Free Music Archive', trust: 'check', kind: 'Full tracks from independent artists', url: 'https://freemusicarchive.org/',
    what: 'Independent music with a licence filter. Some tracks are CC0 or public domain; most use other Creative Commons licences.',
    how: 'Use the licence filter and open each track page. Download from the artist\'s page if it offers it.',
    warn: 'A mix of licences, and some tracks use the site\'s own personal-use licence. Never assume.' },
  { id: 'ccmixter', name: 'ccMixter', trust: 'check', kind: 'Remix community, samples and a cappellas', url: 'https://ccmixter.org/',
    what: 'A Creative Commons remix community. Some people upload samples under CC0. It has a public query interface that can filter by licence.',
    how: 'Use the licence filter or the query API with the CC0 licence, then read each upload page.',
    warn: 'Most tracks are CC BY or non-commercial. Remixes carry the rules of everything they used.' },
  { id: 'itch', name: 'itch.io asset packs', trust: 'check', kind: 'Game jam music packs', url: 'https://itch.io/game-assets/tag-music',
    what: 'Many game audio packs, some marked CC0 by their makers.',
    how: 'Open the pack page and look for the licence line and the creator\'s own statement. Download only from the creator\'s page.',
    warn: 'Licence wording is free text. If it is not plainly CC0, treat it as not CC0.' },
  { id: 'musopen', name: 'Musopen', trust: 'check', kind: 'Public domain classical recordings and scores', url: 'https://musopen.org/',
    what: 'Classical music recordings and sheet music made to be free to use.',
    how: 'Read the licence on each recording page: some are public domain or CC0, others use a Creative Commons credit licence. The site may ask you to sign in.',
    warn: 'I could not load its pages while writing this, so check its current terms yourself before relying on it.' },
  { id: 'loc', name: 'Library of Congress: National Jukebox and Citizen DJ', trust: 'age', kind: 'Old US recordings', url: 'https://www.loc.gov/collections/national-jukebox/about-this-collection/rights-and-access/',
    what: 'Historical US recordings the Library has identified as public domain, free to reuse. US recordings from before 1923 entered the US public domain in 2022; recordings from 1923 to 1946 enter it 100 years after they were published.',
    how: 'Read the collection\'s rights and access page and each item\'s rights line. Note the recording year.',
    warn: 'US law only. The song as well as the recording must be free: an old recording of a song that is still protected is not free. Privacy and publicity rights can still matter.' },
  { id: 'oma', name: 'Open Music Archive', trust: 'age', kind: 'Out-of-copyright British and American recordings', url: 'https://www.openmusicarchive.org/',
    what: 'An artist-led project that finds, digitises and shares out-of-copyright recordings, mostly 1920s and 1930s blues, jazz, folk, country and music hall. It states that material is public domain or CC BY-SA 4.0 unless it says otherwise.',
    how: 'Read the rights line on each recording. Items marked CC BY-SA need credit and share-alike, so they are not CC0: log them honestly.',
    warn: 'Mixed: public domain by age for some, CC BY-SA for others. Age depends on the country, and the song and the recording can end on different dates.' },
  { id: 'dahr', name: 'Old records (UCSB, Internet Archive)', trust: 'age', kind: '1920s 78rpm recordings', url: 'https://adp.library.ucsb.edu/index.php/resources/detail/516',
    what: 'A large library of 78rpm records, digitised. In the US, recordings from 1925 entered the public domain on 1 January 2026.',
    how: 'Use the discography entry to confirm the recording date and the composer. Keep the catalogue number.',
    warn: 'Outside the US the dates differ. The composition may have a later expiry than the recording. Digitisation noise, speed and condition vary.' },
  { id: 'scores', name: 'IMSLP and Mutopia (public domain scores)', trust: 'age', kind: 'Scores to perform and record yourself', url: 'https://imslp.org/',
    what: 'Public domain sheet music. If you perform a public domain piece and record it yourself, the recording is yours to dedicate.',
    how: 'Use the original or a clearly public domain edition. Record it yourself, then log it as Made by me.',
    warn: 'Modern editions and arrangements can be protected even when the piece is not. Check which edition you are using.' },
];

/** Things that look free but are not CC0. Learning these saves the most time. */
export const NOT_CC0 = [
  ['"Royalty-free" or "free for commercial use"', 'This is a site\'s own permission, with its own rules. It is not CC0, and the rules can change.'],
  ['Pixabay music', 'Pixabay\'s own content licence, not CC0. It limits selling content on its own, using recognisable brands, and more.'],
  ['"No attribution required"', 'Many licences say this and still limit other things (no resale, no use in a pack).'],
  ['Collections that gather "CC0 music" from many sites', 'One public collection of this kind includes tracks from sources such as Pixabay and Chosic next to real CC0 ones. A label on a pile is not evidence: go to each original page.'],
  ['CC BY, CC BY-SA, CC BY-NC', 'Creative Commons, but not CC0. They ask for credit, sharing the same way, or no commercial use.'],
  ['Covers, remixes and sample-based tracks', 'The new recording may be free while the song or the sample is not.'],
  ['A site that has closed (for example FreePD, closed in 2025)', 'Copies on other sites have no first-hand licence statement. Treat them as unknown until you can show where the licence came from.'],
  ['Anything with no licence stated', 'No licence does not mean free. It means all rights reserved.'],
];
