/* The Word Lab's words. Written in plain English: short sentences, one idea each, everyday words, the same word for the same thing.
   Rules for adding a word are in README.md in this folder. `cat` is one of: words, web, music, vr, code. `see` is an optional place to try it. */
export const CATS = { words: 'Words', web: 'The web', music: 'Music', vr: 'VR and 3D', code: 'Code' };

export const TERMS = [
  /* ---- words ---- */
  { id: 'portmanteau', cat: 'words', emoji: '🧩', term: 'portmanteau', say: 'port-MAN-toh',
    plain: 'A new word made by joining two words. The new word keeps parts of both.', example: 'breakfast + lunch = brunch. Clank + Cog = ClankCog.' },
  { id: 'camelcase', cat: 'words', emoji: '🐫', term: 'CamelCase', say: 'CAM-ul case',
    plain: 'A way to write two or more words as one word. Each new word starts with a capital letter. The capital letters look like the humps of a camel.', example: 'SparkSprocket = Spark + Sprocket.' },
  { id: 'alliteration', cat: 'words', emoji: '🔤', term: 'alliteration', say: 'uh-lit-er-AY-shun',
    plain: 'When words next to each other start with the same sound.', example: 'Beep Bolt. Pixel Patch. Wobble Wire.' },
  { id: 'glossary', cat: 'words', emoji: '📖', term: 'glossary', say: 'GLOSS-uh-ree',
    plain: 'A short list of words with their meanings. You are reading one now.', example: 'This page is a glossary.' },
  { id: 'accessibility', cat: 'words', emoji: '♿', term: 'accessibility', say: 'ak-SESS-ih-BIL-ih-tee',
    plain: 'Making things easy to use for everyone. This includes people who cannot see well, cannot hear, find it hard to move, or find it hard to read.', example: 'Big buttons, clear words and a calm mode are accessibility.' },
  { id: 'screenreader', cat: 'words', emoji: '🔊', term: 'screen reader', say: 'screen REE-der',
    plain: 'A tool that reads the screen out loud. People who cannot see well often use one.', example: 'It reads the button names to you.' },
  { id: 'feedback', cat: 'words', emoji: '💬', term: 'feedback', say: 'FEED-back',
    plain: 'What you tell the maker about their work: an idea, a problem, or a thank you.', example: 'Glass Groove has a “Send feedback” button.', see: { label: 'Glass Groove', href: 'https://dredarkroom.github.io/GlassGroove/' } },
  { id: 'licence', cat: 'words', emoji: '📜', term: 'licence', say: 'LY-sence',
    plain: 'The rules about how you may use something. “All rights reserved” means: please ask the maker first.', example: 'Most things here are all rights reserved for now.' },

  /* ---- the web ---- */
  { id: 'browser', cat: 'web', emoji: '🌐', term: 'browser', say: 'BROW-zer',
    plain: 'The app you use to open websites. Chrome, Safari, Firefox and Edge are browsers.', example: 'You are reading this in a browser.' },
  { id: 'webapp', cat: 'web', emoji: '📱', term: 'web app', say: 'web app',
    plain: 'A website that works like an app. You do not need a store to get it.', example: 'Glass Groove is a web app.', see: { label: 'Glass Groove', href: 'https://dredarkroom.github.io/GlassGroove/' } },
  { id: 'offline', cat: 'web', emoji: '📴', term: 'offline', say: 'OFF-line',
    plain: 'Working with no internet. After the first visit, some of these labs can work offline.', example: 'Turn on aeroplane mode and Glass Groove still plays.' },
  { id: 'install', cat: 'web', emoji: '📲', term: 'install (add to home screen)', say: 'in-STALL',
    plain: 'Putting a web app on your phone so it has an icon, like other apps.', example: 'In Chrome, open the menu and choose “Add to Home screen”.' },
  { id: 'serviceworker', cat: 'web', emoji: '⚙️', term: 'service worker', say: 'SIR-viss WUR-ker',
    plain: 'A small helper program in your browser. It keeps the files of a page so the page can open with no internet.', example: 'It is how the offline mode works.' },
  { id: 'cache', cat: 'web', emoji: '🗄️', term: 'cache', say: 'cash',
    plain: 'A place on your device where files are kept for later, so they open faster.', example: 'The service worker keeps files in a cache.' },
  { id: 'pixel', cat: 'web', emoji: '🟦', term: 'pixel', say: 'PIX-ul',
    plain: 'One tiny dot of a picture on a screen. Many pixels together make an image.', example: 'A phone screen has millions of pixels.' },
  { id: 'canvas', cat: 'web', emoji: '🖼️', term: 'canvas', say: 'CAN-vus',
    plain: 'A blank area on a web page where a program can draw pictures.', example: 'The fog you wipe in Glass Groove is drawn on a canvas.' },
  { id: 'fps', cat: 'web', emoji: '🎞️', term: 'FPS (frames per second)', say: 'eff-pee-ESS',
    plain: 'How many pictures a screen shows each second. More frames make movement look smoother.', example: '60 FPS looks smoother than 20 FPS.' },
  { id: 'latency', cat: 'web', emoji: '⏱️', term: 'latency', say: 'LAY-ten-see',
    plain: 'A short delay. In music, it is the time between your touch and the sound.', example: 'Low latency means the sound comes at once.' },
  { id: 'haptics', cat: 'web', emoji: '📳', term: 'haptics', say: 'HAP-tiks',
    plain: 'Small vibrations from your phone that you feel as touch.', example: 'Your phone buzzes on the beat.' },

  /* ---- music ---- */
  { id: 'synthesiser', cat: 'music', emoji: '🎹', term: 'synthesiser (synth)', say: 'SIN-thuh-sy-zer',
    plain: 'A machine or program that makes sound from numbers, not from a recording.', example: 'Every sound in these labs is made live by a synthesiser.', see: { label: 'Darklabs FM', href: '../fm/' } },
  { id: 'beat', cat: 'music', emoji: '🥁', term: 'beat', say: 'beet',
    plain: 'The steady pulse of music, like a heartbeat. You can tap your foot to it.', example: 'Tap, tap, tap, tap. That is four beats.' },
  { id: 'bpm', cat: 'music', emoji: '🕒', term: 'BPM (beats per minute)', say: 'bee-pee-EM',
    plain: 'How fast the music is. 120 BPM means 120 beats in one minute.', example: 'Drum and bass is fast, about 170 BPM.' },
  { id: 'tempo', cat: 'music', emoji: '🏃', term: 'tempo', say: 'TEM-poh',
    plain: 'The speed of music. It is measured in BPM.', example: 'Slow tempo, fast tempo.' },
  { id: 'loop', cat: 'music', emoji: '🔁', term: 'loop', say: 'loop',
    plain: 'A short piece of sound that plays again and again.', example: 'A four-beat drum loop.' },
  { id: 'drums', cat: 'music', emoji: '🥁', term: 'kick, snare and hi-hat', say: 'kick, snair, HY-hat',
    plain: 'The three main drum sounds. The kick is low and deep (boom). The snare is sharp (crack). The hi-hat is thin and metal (tss).', example: 'Boom, crack, boom, crack.' },
  { id: 'bass', cat: 'music', emoji: '🔉', term: 'bass', say: 'base',
    plain: 'Deep, low notes. You can often feel them in your chest.', example: 'Turn up the bass.' },
  { id: 'rise', cat: 'music', emoji: '📈', term: 'rise (build-up)', say: 'rize',
    plain: 'A part of a song where the sound climbs higher and gets more tense, before a drop.', example: 'In Glass Groove, hold Rise to build the tension.' },
  { id: 'drop', cat: 'music', emoji: '💥', term: 'drop', say: 'drop',
    plain: 'The moment in dance music when the full beat comes back strong, after a rise.', example: 'Let go of Rise and the drop lands on the beat.' },
  { id: 'filter', cat: 'music', emoji: '🎚️', term: 'filter', say: 'FIL-ter',
    plain: 'A tool that takes some sounds out. A low-pass filter keeps the deep sounds and removes the high ones.', example: 'Open the filter and the sound gets brighter.' },
  { id: 'reverb', cat: 'music', emoji: '🏛️', term: 'reverb', say: 'REE-verb',
    plain: 'The echo of a room. Reverb makes a sound feel like it is in a big space.', example: 'A voice in a church has a lot of reverb.' },
  { id: 'sample', cat: 'music', emoji: '🎙️', term: 'sample', say: 'SAM-pul',
    plain: 'A short recording used inside music. These labs make their sounds live, so they use no samples.', example: 'A recorded drum hit is a sample.' },
  { id: 'scale', cat: 'music', emoji: '🎼', term: 'scale and mood', say: 'skale',
    plain: 'A scale is a set of notes that sound good together. Different scales give different moods, such as dark or bright.', example: 'A minor scale often sounds dark.' },
  { id: 'midi', cat: 'music', emoji: '🎛️', term: 'MIDI', say: 'MID-ee',
    plain: 'A language that music gadgets use to talk to each other. It sends notes, not sound.', example: 'A MIDI keyboard can play a synth on your phone.' },
  { id: 'kaleidoscope', cat: 'music', emoji: '🔮', term: 'kaleidoscope', say: 'kuh-LY-duh-skope',
    plain: 'A picture made of mirrored pieces that repeat, like a snowflake that moves.', example: 'The moving pictures in DevelopDrop.', see: { label: 'DevelopDrop', href: 'https://dredarkroom.github.io/DevelopDrop/' } },
  { id: 'synaesthesia', cat: 'music', emoji: '🌈', term: 'synaesthesia', say: 'sin-es-THEE-zha',
    plain: 'When one sense is felt through another. Some people see colours when they hear music. Many of us link high sounds with light colours.', example: 'Surge in Glass Groove makes the colours climb with the sound.' },

  /* ---- VR and 3D ---- */
  { id: 'vr', cat: 'vr', emoji: '🥽', term: 'VR (virtual reality)', say: 'vee-AR',
    plain: 'A headset that shows you a 3D world that fills your view.', example: 'You can look around inside a VR world.', see: { label: 'VR Lab', href: '../vr/' } },
  { id: 'webxr', cat: 'vr', emoji: '🌍', term: 'WebXR', say: 'web-ex-AR',
    plain: 'A way for websites to use VR headsets. You do not need to install an app.', example: 'The VR Lab has a WebXR example.', see: { label: 'VR Lab', href: '../vr/' } },
  { id: 'threejs', cat: 'vr', emoji: '🧊', term: 'three.js', say: 'three jay-ess',
    plain: 'A free code library that helps websites show 3D pictures.', example: 'The 3D icons on the home page use three.js.' },

  /* ---- code ---- */
  { id: 'code', cat: 'code', emoji: '💻', term: 'code', say: 'code',
    plain: 'Instructions written for a computer. People who write code are called programmers.', example: 'Every button is made by code.' },
  { id: 'bug', cat: 'code', emoji: '🐛', term: 'bug', say: 'bug',
    plain: 'A mistake in a program that makes it do the wrong thing.', example: 'We fix bugs when people tell us about them.' },
  { id: 'glitch', cat: 'code', emoji: '⚡', term: 'glitch', say: 'glich',
    plain: 'A small, short fault. It can look or sound strange. In Darklabs, glitch is also a style.', example: 'The shaking red and blue letters are a glitch style.' },
  { id: 'repo', cat: 'code', emoji: '📁', term: 'repository (repo)', say: 'ree-POZ-ih-tor-ee',
    plain: 'A folder that keeps all the files of a project, and a list of every change.', example: 'Darklabs lives in a repo on GitHub.', see: { label: 'Darklabs on GitHub', href: 'https://github.com/DreDarkroom/darklabs' } },
];
