/* The Word Lab's words. Written in plain English: short sentences, one idea each, everyday words, the same word for the same thing.
   Rules for adding a word are in README.md in this folder. `cat` is one of: words, web, music, vr, code. `see` is an optional place to try it. */
export const CATS = { words: 'Words', web: 'The web', music: 'Music', vr: 'VR and 3D', code: 'Code' };

export const TERMS = [
  /* ---- words ---- */
  { id: 'portmanteau', cat: 'words', emoji: '🧩', term: 'portmanteau', say: 'port-MAN-toh',
    plain: 'A new word made by joining two words. The new word keeps parts of both.', example: 'breakfast + lunch = brunch. Clank + Cog = ClankCog.' },
  { id: 'camelcase', cat: 'words', emoji: '🐫', term: 'CamelCase', say: 'CAM-ul case',
    plain: 'A way to write two or more words as one word, where each new word starts with a capital letter. The capitals look like the humps of a camel.', example: 'SparkSprocket = Spark + Sprocket.' },
  { id: 'alliteration', cat: 'words', emoji: '🔤', term: 'alliteration', say: 'uh-lit-er-AY-shun',
    plain: 'When words next to each other start with the same sound.', example: 'Beep Bolt. Pixel Patch. Wobble Wire.' },
  { id: 'glossary', cat: 'words', emoji: '📖', term: 'glossary', say: 'GLOSS-uh-ree',
    plain: 'A short list of words with their meanings. You are reading one now.', example: 'This page is a glossary.' },
  { id: 'accessibility', cat: 'words', emoji: '♿', term: 'accessibility', say: 'ak-SESS-ih-BIL-ih-tee',
    plain: 'Making things easy to use for everyone. This includes people who cannot see well, cannot hear, find it hard to move, or find it hard to read.', example: 'Big buttons, clear words and a calm mode are accessibility.' },
  { id: 'screenreader', cat: 'words', emoji: '🔊', term: 'screen reader', say: 'screen REE-der',
    plain: 'A tool that reads the screen out loud. People who cannot see well often use one.', example: 'It reads the button names to you.' },
  { id: 'feedback', cat: 'words', emoji: '💬', term: 'feedback', say: 'FEED-back',
    plain: 'What you tell the maker about their work: an idea, a problem, or a thank you.', example: 'Glass Groove has a “Send feedback” button.', see: { label: 'Glass Groove', href: 'https://dredarkroom.github.io/GlassGroove/' } },
  { id: 'licence', cat: 'words', emoji: '📜', term: 'licence', say: 'LY-sence',
    plain: 'The rules about how you may use something. “All rights reserved” means: please ask the maker first.', example: 'Most things here are all rights reserved for now.' },
  { id: 'opensource', cat: 'words', emoji: '🔓', term: 'open source', say: 'OH-pen SORSS',
    plain: 'Code that anyone is allowed to see, use, and change. It is built by people working together.', example: 'Linux is an open source system.' },
  { id: 'creativecommons', cat: 'words', emoji: '🤝', term: 'Creative Commons', say: 'kree-AY-tiv KOM-munz',
    plain: 'A set of free licences. They let a maker share their work and say exactly what others can do with it.', example: 'CC0 is a Creative Commons licence.' },
  { id: 'publicdomain', cat: 'words', emoji: '🏛️', term: 'public domain', say: 'PUB-lik doh-MANE',
    plain: 'Work that belongs to everyone. No one owns it, so anyone can use it.', example: 'Very old books are in the public domain.' },
  { id: 'attribution', cat: 'words', emoji: '🗣️', term: 'attribution', say: 'at-ri-BYOO-shun',
    plain: 'Giving credit to the person who made something. Some licences say you must do this.', example: 'You put their name in the attribution list.' },
  { id: 'provenance', cat: 'words', emoji: '🧾', term: 'provenance', say: 'PROV-en-unss',
    plain: 'A record of where something came from and who made it. It helps you show that you are allowed to use it.', example: 'Keep a provenance sheet for your sounds.' },
  { id: 'checksum', cat: 'words', emoji: '🔢', term: 'checksum (fingerprint)', say: 'CHECK-sum',
    plain: 'A unique code made from a file. If the file changes even a tiny bit, the code changes completely.', example: 'A checksum proves the file is exactly the same one.' },
  { id: 'plainlanguage', cat: 'words', emoji: '🗣️', term: 'plain language', say: 'plane LANG-gwij',
    plain: 'Writing that is clear and simple. It helps everyone understand quickly.', example: 'This glossary uses plain language.' },
  { id: 'alttext', cat: 'words', emoji: '🖼️', term: 'alt text', say: 'alt text',
    plain: 'A short description of a picture. A screen reader reads it out loud for people who cannot see the picture.', example: 'The alt text says "a little red robot".' },
  { id: 'contrast', cat: 'words', emoji: '🌗', term: 'contrast', say: 'KON-trast',
    plain: 'How different a colour is from the background. High contrast makes text easy to read.', example: 'Black text on white has high contrast.' },
  { id: 'reducedmotion', cat: 'words', emoji: '🛑', term: 'reduced motion', say: 're-DOOST MO-shun',
    plain: 'A setting on your device to stop things moving around. It helps people who feel dizzy when screens move.', example: 'Calm mode turns on if you ask for reduced motion.' },
  { id: 'keyboardnav', cat: 'words', emoji: '⌨️', term: 'keyboard navigation', say: 'KEE-bord nav-ih-GAY-shun',
    plain: 'Using a page without a mouse, by pressing keys. You use Tab to jump between buttons.', example: 'Good keyboard navigation is important for accessibility.' },

  /* ---- the web ---- */
  { id: 'https', cat: 'web', emoji: '🔒', term: 'HTTPS', say: 'H-T-T-P-S',
    plain: 'A secure way to send information over the internet. It scrambles the data on its way, so other people cannot read it.', example: 'HTTPS helps keep your password private while it travels.' },
  { id: 'cookie', cat: 'web', emoji: '🍪', term: 'cookie', say: 'KOO-kee',
    plain: 'A tiny file a website leaves on your device to remember you. They are often used to track what you do.', example: 'A cookie remembers what is in your shopping basket.' },
  { id: 'localstorage', cat: 'web', emoji: '📦', term: 'localStorage', say: 'LOH-kul STOR-ij',
    plain: 'A place on your device where a web app can keep small amounts of data. It stays there even when you close the app.', example: 'DarkDesk keeps your notes in localStorage.' },
  { id: 'encryption', cat: 'web', emoji: '🔐', term: 'encryption', say: 'en-KRIP-shun',
    plain: 'Scrambling data using a secret key. You need the key to read the data again.', example: 'Encryption turns your message into a secret code.' },
  { id: 'passcode', cat: 'web', emoji: '🔑', term: 'passcode', say: 'PASS-code',
    plain: 'A secret word or number you choose. It acts as the key for encryption.', example: 'You use a passcode to lock your phone.' },
  { id: 'backup', cat: 'web', emoji: '💾', term: 'backup', say: 'BACK-up',
    plain: 'A copy of your data kept in a different place. It saves you if your device is lost or broken.', example: 'Save a backup file to your computer.' },
  { id: 'api', cat: 'web', emoji: '🔌', term: 'API', say: 'A-P-I',
    plain: 'A way for programs to talk to each other. An API lets a website ask another service for information.', example: 'A weather app uses an API to get the forecast.' },
  { id: 'browser', cat: 'web', emoji: '🌐', term: 'browser', say: 'BROW-zer',
    plain: 'The app you use to open websites. Chrome, Safari, Firefox and Edge are browsers.', example: 'You are reading this in a browser.' },
  { id: 'webapp', cat: 'web', emoji: '📱', term: 'web app', say: 'web app',
    plain: 'A website that works like an app. You do not need a store to get it.', example: 'Glass Groove is a web app.', see: { label: 'Glass Groove', href: 'https://dredarkroom.github.io/GlassGroove/' } },
  { id: 'offline', cat: 'web', emoji: '📴', term: 'offline', say: 'OFF-line',
    plain: 'Working with no internet. After the first visit, some of these labs can work offline.', example: 'Turn on aeroplane mode and Glass Groove still plays.' },
  { id: 'install', cat: 'web', emoji: '📲', term: 'install (add to home screen)', say: 'in-STALL',
    plain: 'Putting a web app on your phone so it has an icon, like other apps.', example: 'In Chrome, open the menu and choose “Add to Home screen”.' },
  { id: 'serviceworker', cat: 'web', emoji: '⚙️', term: 'service worker', say: 'SIR-viss WUR-ker',
    plain: 'A small helper program in your browser. It keeps the files of a page so the page can open with no internet.', example: 'It is how the offline mode works.' },
  { id: 'cache', cat: 'web', emoji: '🗄️', term: 'cache', say: 'cash',
    plain: 'A place on your device where files are kept for later, so they open faster.', example: 'The service worker keeps files in a cache.' },
  { id: 'pixel', cat: 'web', emoji: '🟦', term: 'pixel', say: 'PIX-ul',
    plain: 'One tiny dot of a picture on a screen. Many pixels together make an image.', example: 'A phone screen has millions of pixels.' },
  { id: 'canvas', cat: 'web', emoji: '🖼️', term: 'canvas', say: 'CAN-vus',
    plain: 'A blank area on a web page where a program can draw pictures.', example: 'The fog you wipe in Glass Groove is drawn on a canvas.' },
  { id: 'fps', cat: 'web', emoji: '🎞️', term: 'FPS (frames per second)', say: 'eff-pee-ESS',
    plain: 'How many pictures a screen shows each second. More frames make movement look smoother.', example: '60 FPS looks smoother than 20 FPS.' },
  { id: 'latency', cat: 'web', emoji: '⏱️', term: 'latency', say: 'LAY-ten-see',
    plain: 'A short delay. In music, it is the time between your touch and the sound.', example: 'Low latency means the sound comes at once.' },
  { id: 'haptics', cat: 'web', emoji: '📳', term: 'haptics', say: 'HAP-tiks',
    plain: 'Small vibrations from your phone that you feel as touch.', example: 'Your phone buzzes on the beat.' },

  /* ---- music ---- */
  { id: 'swing', cat: 'music', emoji: '🕺', term: 'swing', say: 'swing',
    plain: 'When the beats in music are uneven, like a skip or a bounce. It makes the rhythm feel human.', example: 'Jazz and hip-hop use a lot of swing.' },
  { id: 'quantise', cat: 'music', emoji: '📏', term: 'quantise', say: 'KWON-tyze',
    plain: 'Moving notes to put them perfectly on the beat. It makes music sound tight and exact.', example: 'A drum machine quantises your hits.' },
  { id: 'sidechain', cat: 'music', emoji: '🦆', term: 'sidechain', say: 'SYDE-chane',
    plain: 'Making one sound dip down when another plays. It often makes the bass duck out of the way for the kick drum.', example: 'Sidechain makes dance music pump.' },
  { id: 'compressor', cat: 'music', emoji: '🗜️', term: 'compressor', say: 'kum-PRESS-er',
    plain: 'A tool that turns down the loudest parts of a sound. The quiet parts can then be heard better, so the volume stays even.', example: 'A compressor makes a vocal clear all the way through.' },
  { id: 'eq', cat: 'music', emoji: '🎛️', term: 'EQ (equaliser)', say: 'ee-KYOO',
    plain: 'A tool to change the tone of a sound. You can turn up the bass or turn down the high parts.', example: 'Use EQ to make a guitar sound less muddy.' },
  { id: 'samplerate', cat: 'music', emoji: '📶', term: 'sample rate', say: 'SAM-pul rate',
    plain: 'How many times a second sound is measured to turn it into numbers. Higher numbers can catch higher notes.', example: 'A CD uses a sample rate of 44,100 times a second.' },
  { id: 'bitdepth', cat: 'music', emoji: '📉', term: 'bit depth', say: 'bit depth',
    plain: 'How much detail is kept each time sound is measured. More detail means less noise in quiet parts.', example: 'A CD uses 16-bit depth.' },
  { id: 'stem', cat: 'music', emoji: '🎶', term: 'stem', say: 'stem',
    plain: 'One part of a song saved on its own. The drums, the bass, and the voice are stems.', example: 'DJs use stems to mix parts of songs together.' },
  { id: 'master', cat: 'music', emoji: '💽', term: 'master', say: 'MASS-ter',
    plain: 'The final, finished song. It has been polished and is ready to play everywhere.', example: 'The master goes to the streaming service.' },
  { id: 'mix', cat: 'music', emoji: '🎚️', term: 'mix', say: 'mix',
    plain: 'How all the parts of a song are balanced together. A good mix lets you hear everything clearly.', example: 'Turn the vocal up in the mix.' },
  { id: 'loudness', cat: 'music', emoji: '🔊', term: 'loudness (LUFS)', say: 'LOUD-ness, lufs',
    plain: 'How loud a song feels to our ears. Streaming services use it to keep songs at the same level.', example: 'The loudness matches the other songs on the playlist.' },
  { id: 'clipping', cat: 'music', emoji: '✂️', term: 'clipping', say: 'CLIP-ping',
    plain: 'When a sound is too loud for a machine, and the top gets cut off. It sounds harsh and broken.', example: 'Turn it down to stop the clipping.' },
  { id: 'waveform', cat: 'music', emoji: '〰️', term: 'waveform', say: 'WAVE-form',
    plain: 'A picture of sound over time. A loud sound makes a tall wave.', example: 'You edit sound by looking at the waveform.' },
  { id: 'spectrogram', cat: 'music', emoji: '🌈', term: 'spectrogram', say: 'SPECK-tro-gram',
    plain: 'A picture of sound that shows low notes at the bottom and high notes at the top. Brighter colours mean louder parts.', example: 'A spectrogram shows a bird song clearly.' },
  { id: 'synthesiser', cat: 'music', emoji: '🎹', term: 'synthesiser (synth)', say: 'SIN-thuh-sy-zer',
    plain: 'A machine or program that makes sound from numbers, not from a recording.', example: 'Every sound in these labs is made live by a synthesiser.', see: { label: 'Darklabs FM', href: '../fm/' } },
  { id: 'beat', cat: 'music', emoji: '🥁', term: 'beat', say: 'beet',
    plain: 'The steady pulse of music, like a heartbeat. You can tap your foot to it.', example: 'Tap, tap, tap, tap. That is four beats.' },
  { id: 'bpm', cat: 'music', emoji: '🕒', term: 'BPM (beats per minute)', say: 'bee-pee-EM',
    plain: 'How fast the music is. 120 BPM means 120 beats in one minute.', example: 'Drum and bass is fast, about 170 BPM.' },
  { id: 'tempo', cat: 'music', emoji: '🏃', term: 'tempo', say: 'TEM-poh',
    plain: 'The speed of music. It is measured in BPM.', example: 'Slow tempo, fast tempo.' },
  { id: 'loop', cat: 'music', emoji: '🔁', term: 'loop', say: 'loop',
    plain: 'A short piece of sound that plays again and again.', example: 'A four-beat drum loop.' },
  { id: 'drums', cat: 'music', emoji: '🥁', term: 'kick, snare and hi-hat', say: 'kick, snair, HY-hat',
    plain: 'These are the three main drum sounds. The kick is low and deep (boom), the snare is sharp (crack) and the hi-hat is thin and metal (tss).', example: 'Boom, crack, boom, crack.' },
  { id: 'bass', cat: 'music', emoji: '🔉', term: 'bass', say: 'base',
    plain: 'Deep, low notes. You can often feel them in your chest.', example: 'Turn up the bass.' },
  { id: 'rise', cat: 'music', emoji: '📈', term: 'rise (build-up)', say: 'rize',
    plain: 'A part of a song where the sound climbs higher and gets more tense, before a drop.', example: 'In Glass Groove, hold Rise to build the tension.' },
  { id: 'drop', cat: 'music', emoji: '💥', term: 'drop', say: 'drop',
    plain: 'The moment in dance music when the full beat comes back strong, after a rise.', example: 'Let go of Rise and the drop lands on the beat.' },
  { id: 'filter', cat: 'music', emoji: '🎚️', term: 'filter', say: 'FIL-ter',
    plain: 'A tool that takes some sounds out. A low-pass filter keeps the deep sounds and removes the high ones.', example: 'Open the filter and the sound gets brighter.' },
  { id: 'reverb', cat: 'music', emoji: '🏛️', term: 'reverb', say: 'REE-verb',
    plain: 'The echo of a room. Reverb makes a sound feel like it is in a big space.', example: 'A voice in a church has a lot of reverb.' },
  { id: 'sample', cat: 'music', emoji: '🎙️', term: 'sample', say: 'SAM-pul',
    plain: 'A short recording used inside music. These labs make their sounds live, so they use no samples.', example: 'A recorded drum hit is a sample.' },
  { id: 'scale', cat: 'music', emoji: '🎼', term: 'scale and mood', say: 'skale',
    plain: 'A scale is a set of notes that sound good together. Different scales give different moods, such as dark or bright.', example: 'A minor scale often sounds dark.' },
  { id: 'midi', cat: 'music', emoji: '🎛️', term: 'MIDI', say: 'MID-ee',
    plain: 'A language that music gadgets use to talk to each other. It sends notes, not sound.', example: 'A MIDI keyboard can play a synth on your phone.' },
  { id: 'kaleidoscope', cat: 'music', emoji: '🔮', term: 'kaleidoscope', say: 'kuh-LY-duh-skope',
    plain: 'A picture made of mirrored pieces that repeat, like a snowflake that moves.', example: 'The moving pictures in DevelopDrop.', see: { label: 'DevelopDrop', href: 'https://dredarkroom.github.io/DevelopDrop/' } },
  { id: 'synaesthesia', cat: 'music', emoji: '🌈', term: 'synaesthesia', say: 'sin-es-THEE-zha',
    plain: 'When one sense is felt through another, so some people see colours when they hear music. Many of us link high sounds with light colours.', example: 'Surge in Glass Groove makes the colours climb with the sound.' },

  /* ---- VR and 3D ---- */
  { id: 'vr', cat: 'vr', emoji: '🥽', term: 'VR (virtual reality)', say: 'vee-AR',
    plain: 'A headset that shows you a 3D world that fills your view.', example: 'You can look around inside a VR world.', see: { label: 'VR Lab', href: '../vr/' } },
  { id: 'webxr', cat: 'vr', emoji: '🌍', term: 'WebXR', say: 'web-ex-AR',
    plain: 'A way for websites to use VR headsets. You do not need to install an app.', example: 'The VR Lab has a WebXR example.', see: { label: 'VR Lab', href: '../vr/' } },
  { id: 'threejs', cat: 'vr', emoji: '🧊', term: 'three.js', say: 'three jay-ess',
    plain: 'A free code library that helps websites show 3D pictures.', example: 'The 3D icons on the home page use three.js.' },

  /* ---- code ---- */
  { id: 'code', cat: 'code', emoji: '💻', term: 'code', say: 'code',
    plain: 'Instructions written for a computer. People who write code are called programmers.', example: 'Every button is made by code.' },
  { id: 'bug', cat: 'code', emoji: '🐛', term: 'bug', say: 'bug',
    plain: 'A mistake in a program that makes it do the wrong thing.', example: 'We fix bugs when people tell us about them.' },
  { id: 'glitch', cat: 'code', emoji: '⚡', term: 'glitch', say: 'glich',
    plain: 'A small, short fault that can look or sound strange. In Darklabs, glitch is also a style.', example: 'The shaking red and blue letters are a glitch style.' },
  { id: 'repo', cat: 'code', emoji: '📁', term: 'repository (repo)', say: 'ree-POZ-ih-tor-ee',
    plain: 'A folder that keeps all the files of a project, and a list of every change.', example: 'Darklabs lives in a repo on GitHub.', see: { label: 'Darklabs on GitHub', href: 'https://github.com/DreDarkroom/darklabs' } },
];
