/* Generated by tools/hub/build_hub.py from the home page's cards: the public facts only. Edit hub_data.py, not this file. */
export const SEEDS = [
 {
  "id": "developdrop",
  "title": "DevelopDrop",
  "blurb": "A small browser instrument: a bass synth, three drummers and a kaleidoscope you wipe clear with a squeegee. DreDarkroom, Safelight and SquidgySqueegee are the DJ aliases.",
  "url": "https://dredarkroom.github.io/DevelopDrop/",
  "status": "Live",
  "group": "featured"
 },
 {
  "id": "wordlab",
  "title": "Word Lab",
  "blurb": "Plain-English meanings for the words used across Darklabs, with a portmanteau maker, read-aloud buttons, a robot-name generator and easy-reading settings. Made so that people who find tech words hard, or who do not speak English as a first language, can follow along.",
  "url": "/darklabs/learn/",
  "status": "Live",
  "group": "on the line"
 },
 {
  "id": "wipelight",
  "title": "Glass Groove",
  "blurb": "Wipe the fog off a glowing picture and make music with your thumbs. A bass, three drummers and a picture that reacts to everything you touch, built for one hand on a phone. Two-finger double tap for a Surge: a long rise with a countdown and colours that climb with the sound. Keeps playing when you leave, works offline, and shares a beat as a link.",
  "url": "https://dredarkroom.github.io/GlassGroove/",
  "status": "Building",
  "group": "on the line"
 },
 {
  "id": "vrlab",
  "title": "VR Lab",
  "blurb": "A short, honest course in making VR apps in the browser with three.js and WebXR, with a live example you can step into. Plus where to point your support, and a way to get alerts.",
  "url": "/darklabs/vr/",
  "status": "Live",
  "group": "on the line"
 },
 {
  "id": "darklabsfm",
  "title": "Darklabs FM",
  "blurb": "A radio with no recordings in it. Drum & bass front and centre, plus breaks, hard dark techno and soft melodic techno. Every sound is synthesised live in your browser, and every track is composed from a seed. Tell me what you think: your feedback goes straight to my phone.",
  "url": "/darklabs/fm/",
  "status": "Live",
  "group": "on the line"
 },
 {
  "id": "penrosepulse",
  "title": "PenrosePulse",
  "blurb": "An infinite staircase of sound. It starts as one soft felt piano, then you press Climb: a pad breathes in, a marimba circles your phrase, a shuffling shaker and a soft tom arrive, the chord swells and rolls into the drop — then the key lifts a whole step and it climbs again, forever. Endless-zoom light visuals, an endlessly rising staircase tone, touch / keys / pads / MIDI, and it installs offline.",
  "url": "/darklabs/penrosepulse/",
  "status": "Live",
  "group": "on the line"
 },
 {
  "id": "chunguscello",
  "title": "ChungusCello",
  "blurb": "A physically-modelled cello — every note is a simulated bowed string, not a recording. Bow it, pluck it, tremolo it, or chug it through the Chungus amp. Fretless touch fingerboard with slides and vibrato, a loop station, sing-to-play, a tuner, and a sampler that turns any sound into an instrument (MeowSynth's meow included). MIDI and MPE in and out, WAV/MIDI/stem exports with a Reaper project, and it installs offline.",
  "url": "/darklabs/chunguscello/",
  "status": "Live",
  "group": "on the line"
 },
 {
  "id": "meowsynth",
  "title": "MeowSynth",
  "blurb": "A tiny browser synth made entirely of human \"meow\" impressions. Play chromatic melodies and trigger mood pads with a single click.",
  "url": "/darklabs/meowsynth/",
  "status": "Live",
  "group": "on the line"
 },
 {
  "id": "monkeybeat",
  "title": "MonkeyBeat",
  "blurb": "A browser-based drum machine with customizable pads, samples, and sequencing. Build your rhythm with style.",
  "url": "/darklabs/monkeybeat/",
  "status": "Live",
  "group": "on the line"
 },
 {
  "id": "both",
  "title": "Both Together",
  "blurb": "Run MeowSynth and MonkeyBeat side by side on one page (stacked on phones). Play the meows over your own beat.",
  "url": "/darklabs/both/",
  "status": "Live",
  "group": "on the line"
 },
 {
  "id": "drumdj",
  "title": "DarkDeck",
  "blurb": "Modelled acoustic drum kit with sequencer, a two-deck DJ mixer (load your own tracks), a sampler, a master effects rack and an SFX maker. Bring your own audio or use the built-in demos.",
  "url": "/darklabs/drumdj/",
  "status": "Live",
  "group": "on the line"
 },
 {
  "id": "crate-capture",
  "title": "Crate Capture",
  "blurb": "Find CC0 and public domain music, check the licence properly, keep the proof, and hand it over cleanly. Guides on searching wide and far, a map of 15 sources (and the things that only look free), and a finds log that fingerprints your files and writes the licence sheet. Everything stays on your device.",
  "url": "/darklabs/crate/",
  "status": "Building",
  "group": "in the trays"
 },
 {
  "id": "circuitstomp",
  "title": "CircuitStomp",
  "blurb": "A drum & bass machine built entirely from synthesised robot voices — no samples anywhere. Sequencer with pitch and chance per step, live playing, MIDI in and out, and exports of stems, MIDI and a ready-made Reaper project. Includes 11 lessons and a printable guide.",
  "url": "/darklabs/circuitstomp/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "glowgrain",
  "title": "GlowGrain",
  "blurb": "A sunlit felt piano that blooms: turn up Bloom and a pad, a warm bass, a marimba figure, light percussion, a voice and a self-playing piano wake in turn. Synthesised in the browser, with tape warmth, a loop station and WAV / MIDI export.",
  "url": "/darklabs/glowgrain/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "blueheronbass",
  "title": "BlueHeronBass",
  "blurb": "A five-string bass with a blue heron in its voice: finger, pick, slap, pop, tap and harmonics, a fuzz and envelope-filter amp, a loop station and MIDI. No samples, no sign-up.",
  "url": "/darklabs/blueheronbass/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "radio",
  "title": "Darklabs Radio",
  "blurb": "A cleared-for-use radio station with a TTS presenter reading idents between tracks — built to be hosted or broadcast, with room to adapt to other environments later on.",
  "url": "/darklabs/radio/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "cratecall",
  "title": "CrateCall",
  "blurb": "An audition tool for the VR game's music and SFX pool — rate tracks Love/Keep/Maybe/Drop, trim and export a loop, and send picks to the team in one click.",
  "url": "/darklabs/cratecall/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "sonicsmithy",
  "title": "Sonic Smithy",
  "blurb": "The SFX counterpart to CrateCall: audition and auto-rate CC0 sound packs, layer and slice/loop them, generate new sci-fi SFX from scratch (with a dedicated Pistol Lab and Rail Lab), then export a Godot-ready folder with a manifest and autoload script.",
  "url": "/darklabs/sonicsmithy/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "dark-cinema-lab",
  "title": "Dark Cinema Lab",
  "blurb": "A dark reference hub for cinema ideas and looks. Work in progress.",
  "url": "/darklabs/dark-cinema-lab/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "promptlab",
  "title": "Prompt Lab",
  "blurb": "A browser-based experimental laboratory for comparing and evaluating AI prompts.",
  "url": "/darklabs/promptlab/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "resonance-core",
  "title": "Resonance Core",
  "blurb": "A game prototype that runs in the browser. Rough edges expected.",
  "url": "/darklabs/resonance-core/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "resonic-toolkit",
  "title": "Resonic CLI Toolkit",
  "blurb": "A command-line generator for Resonic Player: a fast, visual way to build launch arguments for musicians and sound designers.",
  "url": "/darklabs/resonic-toolkit/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "brokebots",
  "title": "BrokeBots",
  "blurb": "An experimental browser game for PC (with a mobile version and two-player potential), made by chain-prompting five independent models. Potentially broken robots here.",
  "url": "https://dredarkroom.github.io/BrokeBots/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "darkography",
  "title": "Darkography",
  "blurb": "The Dre Darkroom photography portfolio.",
  "url": "https://dredarkroom.github.io/darkography/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "throattapper",
  "title": "ThroatTapper",
  "blurb": "Percussion made from throat flicks and taps. Four tap articulations on keys 1–4, plus a chromatic tonal hum across the QWERTY middle row.",
  "url": "/darklabs/throattapper/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "pipeline-test",
  "title": "Pipeline Test",
  "blurb": "A deployment pipeline test page. Nothing to see here. (Probably.)",
  "url": "/darklabs/pipeline-test/",
  "status": "Live",
  "group": "in the trays"
 },
 {
  "id": "idea",
  "title": "IDEA: Drunk Bots",
  "blurb": "Two teams of identical, very drunk bots wander into a huge flat-pack maze, each quite sure they know the way out. Shout directions at your team and be first to get four through the checkout. A quick game with a tabletop VR mode.",
  "url": "/darklabs/idea/",
  "status": "Paused",
  "group": "roadmap"
 },
 {
  "id": "contact-sheet",
  "title": "Contact Sheet",
  "blurb": "A small pipeline that pulls new clips and stills off a VR headset's gallery, renames them cleanly, and gets them ready to publish — unlisted on YouTube until you say otherwise, stills backed up to your own cloud storage.",
  "url": "https://dredarkroom.github.io/contact-sheet/",
  "status": "Live",
  "group": "roadmap"
 },
 {
  "id": "safelight",
  "title": "Safelight",
  "blurb": "A transmission from 2133, played back at 33⅓. A turntable you can play and scratch, synthesised vinyl crackle, and a crate of hand-printed sleeves. Side A is Safelight; flip it and SquidgySqueegee takes over side B.",
  "url": "/darklabs/safelight/",
  "status": "Testing",
  "group": "roadmap"
 },
 {
  "id": "obscura",
  "title": "Dre Darkroom",
  "blurb": "An experimental preview of the Dre Darkroom homepage. A camera obscura hero, four developer trays, a crimson safelight, two little games and a roll of 24 hidden frames to find.",
  "url": "/darklabs/obscura/",
  "status": "Testing",
  "group": "roadmap"
 },
 {
  "id": "mobile-wip",
  "title": "Mobile first: the workshop",
  "blurb": "Glass Groove is the first of a line of things designed for a phone before anything else. Next on the bench: a one-tap Loop button, a Journey slider, a replay as a link, two phones paired by QR code, and a proper tour. Real-phone testing comes first.",
  "url": "",
  "status": "Paused",
  "group": "roadmap"
 },
 {
  "id": "perf-lab",
  "title": "Performance panel",
  "blurb": "A developer mode for the phone-first projects: frame rate, how far ahead of the audio clock the scheduler is, audio dropouts, memory, battery drain and heat where the browser reports them, with a log you can copy. Measured, not guessed.",
  "url": "",
  "status": "Paused",
  "group": "roadmap"
 },
 {
  "id": "wordlab-more",
  "title": "Word Lab in more languages",
  "blurb": "Human-written or human-checked translations of the main explanations, with the same read-aloud buttons. Machine translation is not enough on its own, so each language waits for someone who speaks it.",
  "url": "",
  "status": "Paused",
  "group": "roadmap"
 },
 {
  "id": "crate-club",
  "title": "Crate Club",
  "blurb": "A small community around Crate Capture: share finds with their proof, see who has checked a track, flag licence problems, follow curators. It needs accounts and a database, so it waits for the server. The plan is in the Crate Capture folder.",
  "url": "",
  "status": "Paused",
  "group": "roadmap"
 },
 {
  "id": "ask-dre",
  "title": "Ask Dre",
  "blurb": "A little chat that answers the way I would, with a lot of music knowledge behind it. It needs a small server to do properly, so it waits for the migration.",
  "url": "",
  "status": "Paused",
  "group": "roadmap"
 },
 {
  "id": "lobby",
  "title": "The Lobby",
  "blurb": "A little 3D lobby you can wander round: a skateboard parked by the door, a fogged-up window, and twelve hidden frames to find. Half sketched, waiting its turn.",
  "url": "",
  "status": "Paused",
  "group": "roadmap"
 },
 {
  "id": "penrose-visuals",
  "title": "PenrosePulse: looping visuals",
  "blurb": "Mirror-and-feedback pictures that loop forever, for the infinite staircase to climb through. An idea in the drawer.",
  "url": "",
  "status": "Paused",
  "group": "roadmap"
 },
 {
  "id": "fm-replies",
  "title": "Darklabs FM: replies",
  "blurb": "Saved feedback, replies, and a private inbox, once there's a proper server to keep them on. For now, feedback goes straight to a phone.",
  "url": "",
  "status": "Paused",
  "group": "roadmap"
 },
 {
  "id": "shared-kit",
  "title": "One shared kit",
  "blurb": "Move every instrument onto the same audio and visual building blocks, so a fix in one place fixes them all.",
  "url": "",
  "status": "Paused",
  "group": "roadmap"
 },
 {
  "id": "darklabs-caps",
  "title": "DarkLabs, with a capital L",
  "blurb": "A visual-only respelling of the name. No links change, nothing breaks, it just looks sharper.",
  "url": "",
  "status": "Paused",
  "group": "roadmap"
 },
 {
  "id": "earshot",
  "title": "Earshot",
  "blurb": "A future audition tool for sorting and rating new material. Not live yet.",
  "url": "",
  "status": "Paused",
  "group": "roadmap"
 }
];
