# Content for the Darklabs hub. Text is carried over from the previous hub; new entries use their own READMEs / repo descriptions.
HERO = dict(
    id="developdrop", icon="&#x1F300;", title="DevelopDrop", badge="FEATURED",
    desc="A small browser instrument: a bass synth, three drummers and a kaleidoscope you wipe clear with a squeegee. "
         "DreDarkroom, Safelight and SquidgySqueegee are the DJ aliases.",
    note="Now showing in the darkroom. Wipe the glass.", href="https://dredarkroom.github.io/DevelopDrop/", btn="Open DevelopDrop",
)

MAIN = [
    dict(id="wordlab", icon="&#x1F4D6;", title="Word Lab", badge="NEW",
         desc="Plain-English meanings for the words used across Darklabs, with a portmanteau maker, read-aloud buttons, a robot-name generator and easy-reading settings. Made so that people who find tech words hard, or who do not speak English as a first language, can follow along.",
         note="short sentences &middot; listen to any word &middot; easy reading, big text, calm mode",
         href="/darklabs/learn/", btn="Open the Word Lab"),
    dict(id="wipelight", icon="&#x1F4A1;", title="Glass Groove", badge="WORK IN PROGRESS",
         desc="Wipe the fog off a glowing picture and make music with your thumbs. A bass, three drummers and a picture that reacts to everything you touch, built for one hand on a phone. Two-finger double tap for a Surge: a long rise with a countdown and colours that climb with the sound. Keeps playing when you leave, works offline, and shares a beat as a link.",
         note="Mobile first &middot; early and still being tested on real phones &middot; feedback and requests welcome",
         href="https://dredarkroom.github.io/GlassGroove/", btn="Open Glass Groove"),
    dict(id="vrlab", icon="&#x1F97D;", title="VR Lab", badge="NEW",
         desc="A short, honest course in making VR apps in the browser with three.js and WebXR, with a live example you can step into. Plus where to point your support, and a way to get alerts.",
         note="eight small lessons &middot; headset optional &middot; no account needed",
         href="/darklabs/vr/", btn="Open the VR Lab"),
    dict(id="darklabsfm", icon="&#x1F4FB;", title="Darklabs FM", badge="NEW",
         desc="A radio with no recordings in it. Drum &amp; bass front and centre, plus breaks, hard dark techno and soft melodic techno. Every sound is synthesised live in your browser, and every track is composed from a seed. Tell me what you think: your feedback goes straight to my phone.",
         note="Synth-generated &middot; produced in the Dark Labs &middot; no samples, no recordings",
         href="/darklabs/fm/", btn="Tune in"),
    dict(id="penrosepulse", icon="&#x1F300;", title="PenrosePulse", badge="NEW",
         desc="An infinite staircase of sound. It starts as one soft felt piano, then you press <em>Climb</em>: a pad breathes in, a marimba circles your phrase, "
              "a shuffling shaker and a soft tom arrive, the chord swells and rolls into the drop &mdash; then the key lifts a whole step and it climbs again, forever. "
              "Endless-zoom light visuals, an endlessly rising staircase tone, touch / keys / pads / MIDI, and it installs offline.",
         note="Play over it or steer it with the Ascent slider &middot; glowing keys and pads that only play notes from the chord &middot; works on phones and in the Quest Browser",
         href="/darklabs/penrosepulse/", btn="Open PenrosePulse"),
    dict(id="chunguscello", icon="&#x1F3BB;", title="ChungusCello", badge="NEW",
         desc="A physically-modelled cello &mdash; every note is a simulated bowed string, not a recording. Bow it, pluck it, tremolo it, or chug it through the Chungus amp. "
              "Fretless touch fingerboard with slides and vibrato, a loop station, sing-to-play, a tuner, and a sampler that turns any sound into an instrument (MeowSynth's meow included). "
              "MIDI and MPE in and out, WAV/MIDI/stem exports with a Reaper project, and it installs offline.",
         note="Works on phones (turn sideways for longer strings) &middot; play it in VR on Meta Quest 2 / 3 from the Quest Browser",
         href="/darklabs/chunguscello/", btn="Open ChungusCello"),
    dict(id="meowsynth", icon="&#x1F431;", title="MeowSynth",
         desc="A tiny browser synth made entirely of human \"meow\" impressions. Play chromatic melodies and trigger mood pads with a single click.",
         href="/darklabs/meowsynth/", btn="Open MeowSynth", apk=True),
    dict(id="monkeybeat", icon="&#x1F435;", title="MonkeyBeat",
         desc="A browser-based drum machine with customizable pads, samples, and sequencing. Build your rhythm with style.",
         href="/darklabs/monkeybeat/", btn="Open MonkeyBeat"),
    dict(id="both", icon="&#x1F3B5;", title="Both Together",
         desc="Run MeowSynth and MonkeyBeat side by side on one page (stacked on phones). Play the meows over your own beat.",
         href="/darklabs/both/", btn="Open Both"),
    dict(id="drumdj", icon="&#x1F941;", title="DarkDeck",
         desc="Modelled acoustic drum kit with sequencer, a two-deck DJ mixer (load your own tracks), a sampler, a master effects rack and an SFX maker. Bring your own audio or use the built-in demos.",
         href="/darklabs/drumdj/", btn="Open DarkDeck"),
]

WIP = [
    dict(id="circuitstomp", icon="&#x1F916;", title="CircuitStomp", big=True,
         desc="A drum &amp; bass machine built entirely from synthesised robot voices &mdash; no samples anywhere. Sequencer with pitch and chance per step, live playing, MIDI in and out, "
              "and exports of stems, MIDI and a ready-made Reaper project. Includes 11 lessons and a printable guide.",
         href="/darklabs/circuitstomp/", btn="Open CircuitStomp"),
    dict(id="glowgrain", icon="&#x2600;&#xFE0F;", title="GlowGrain",
         desc="A sunlit felt piano that blooms: turn up <em>Bloom</em> and a pad, a warm bass, a marimba figure, light percussion, a voice and a self-playing piano wake in turn. "
              "Synthesised in the browser, with tape warmth, a loop station and WAV / MIDI export.",
         note="Parked for now &mdash; PenrosePulse took the spotlight.", href="/darklabs/glowgrain/", btn="Open GlowGrain"),
    dict(id="blueheronbass", icon="&#x1F426;", title="BlueHeronBass",
         desc="A five-string bass with a blue heron in its voice: finger, pick, slap, pop, tap and harmonics, a fuzz and envelope-filter amp, a loop station and MIDI. No samples, no sign-up.",
         href="/darklabs/blueheronbass/", btn="Open BlueHeronBass"),
    dict(id="radio", icon="&#x1F4FB;", title="Darklabs Radio",
         desc="A cleared-for-use radio station with a TTS presenter reading idents between tracks &mdash; built to be hosted or broadcast, with room to adapt to other environments later on.",
         note="Presenter voice is placeholder browser TTS until real voice pops exist. No shared live stream yet &mdash; each listener's browser plays its own loop.",
         href="/darklabs/radio/", btn="Open Darklabs Radio"),
    dict(id="cratecall", icon="&#x1F3A7;", title="CrateCall",
         desc="An audition tool for the VR game's music and SFX pool &mdash; rate tracks Love/Keep/Maybe/Drop, trim and export a loop, and send picks to the team in one click.",
         href="/darklabs/cratecall/", btn="Open CrateCall"),
    dict(id="sonicsmithy", icon="&#x1F528;", title="Sonic Smithy",
         desc="The SFX counterpart to CrateCall: audition and auto-rate CC0 sound packs, layer and slice/loop them, generate new sci-fi SFX from scratch (with a dedicated Pistol Lab and Rail Lab), "
              "then export a Godot-ready folder with a manifest and autoload script.",
         href="/darklabs/sonicsmithy/", btn="Open Sonic Smithy"),
    dict(id="dark-cinema-lab", icon="&#x1F3AC;", title="Dark Cinema Lab",
         desc="A dark reference hub for cinema ideas and looks. Work in progress.",
         href="/darklabs/dark-cinema-lab/", btn="Open Dark Cinema Lab"),
    dict(id="promptlab", icon="&#x1F9EA;", title="Prompt Lab",
         desc="A browser-based experimental laboratory for comparing and evaluating AI prompts.",
         href="/darklabs/promptlab/", btn="Open Prompt Lab"),
    dict(id="resonance-core", icon="&#x1F4A0;", title="Resonance Core",
         desc="A game prototype that runs in the browser. Rough edges expected.",
         href="/darklabs/resonance-core/", btn="Open Resonance Core"),
    dict(id="resonic-toolkit", icon="&#x1F6E0;&#xFE0F;", title="Resonic CLI Toolkit",
         desc="A command-line generator for Resonic Player: a fast, visual way to build launch arguments for musicians and sound designers.",
         href="/darklabs/resonic-toolkit/", btn="Open Resonic Toolkit"),
    dict(id="brokebots", icon="&#x1F9BE;", title="BrokeBots",
         desc="An experimental browser game for PC (with a mobile version and two-player potential), made by chain-prompting five independent models. Potentially broken robots here.",
         href="https://dredarkroom.github.io/BrokeBots/", btn="Open BrokeBots"),
    dict(id="darkography", icon="&#x1F4F7;", title="Darkography",
         desc="The Dre Darkroom photography portfolio.",
         href="https://dredarkroom.github.io/darkography/", btn="Open Darkography"),
    dict(id="throattapper", icon="&#x1F3A4;", title="ThroatTapper", dim=True,
         desc="Percussion made from throat flicks and taps. Four tap articulations on keys 1&ndash;4, plus a chromatic tonal hum across the QWERTY middle row.",
         href="/darklabs/throattapper/", btn="Open ThroatTapper"),
    dict(id="pipeline-test", icon="&#x1F9F0;", title="Pipeline Test", dim=True,
         desc="A deployment pipeline test page. Nothing to see here. (Probably.)",
         href="/darklabs/pipeline-test/", btn="Open Pipeline Test"),
]

SOON = [
    dict(id="idea", icon="&#x1F916;", title="IDEA: Drunk Bots", badge="PLAYABLE PREVIEW",
         desc="Two teams of identical, very drunk bots wander into a huge flat-pack maze, each quite sure they know the way out. Shout directions at your team and be first to get four through the checkout. A quick game with a tabletop VR mode.",
         note="A parody. Not affiliated with any real furniture retailer, living or flat-packed &middot; works on desktop, phones and in VR browsers",
         href="/darklabs/idea/", btn="Let them in"),
    dict(id="contact-sheet", icon="&#x1F39E;&#xFE0F;", title="Contact Sheet",
         desc="A small pipeline that pulls new clips and stills off a VR headset's gallery, renames them cleanly, and gets them ready to publish &mdash; unlisted on YouTube until you say otherwise, stills backed up to your own cloud storage.",
         href="https://dredarkroom.github.io/contact-sheet/", btn="Open Contact Sheet", badge="LIVE"),
    dict(id="safelight", icon="&#x1F4BF;", title="Safelight", sub="// Slow Future", kind="safelight", badge="PREVIEW",
         desc="A transmission from 2133, played back at 33&#8531;. A turntable you can play and scratch, synthesised vinyl crackle, and a crate of hand-printed sleeves. Side A is Safelight; flip it and SquidgySqueegee takes over side B.",
         note="&lambda; 589 nm &middot; sound on &middot; mixes are placeholders for now", href="/darklabs/safelight/", btn="Tune in to Safelight"),
    dict(id="obscura", icon="&#x1F441;&#xFE0F;", title="Dre Darkroom", sub="// Obscura", kind="obscura", badge="PREVIEW",
         desc="An experimental preview of the Dre Darkroom homepage. A camera obscura hero, four developer trays, a crimson safelight, two little games and a roll of 24 hidden frames to find.",
         note="sound on &middot; the more you look, the more you find", href="/darklabs/obscura/", btn="Step into the room"),
    dict(id="mobile-wip", icon="&#x1F4F1;", title="Mobile first: the workshop", teaser=True, badge="BACK BURNER",
         desc="Glass Groove is the first of a line of things designed for a phone before anything else. Next on the bench: a one-tap Loop button, a Journey slider, a replay as a link, two phones paired by QR code, and a proper tour. Real-phone testing comes first."),
    dict(id="perf-lab", icon="&#x1F4CA;", title="Performance panel", teaser=True, badge="BACK BURNER",
         desc="A developer mode for the phone-first projects: frame rate, how far ahead of the audio clock the scheduler is, audio dropouts, memory, battery drain and heat where the browser reports them, with a log you can copy. Measured, not guessed."),
    dict(id="wordlab-more", icon="&#x1F30D;", title="Word Lab in more languages", teaser=True, badge="BACK BURNER",
         desc="Human-written or human-checked translations of the main explanations, with the same read-aloud buttons. Machine translation is not enough on its own, so each language waits for someone who speaks it."),
    dict(id="ask-dre", icon="&#x1F4AC;", title="Ask Dre", teaser=True, badge="BACK BURNER",
         desc="A little chat that answers the way I would, with a lot of music knowledge behind it. It needs a small server to do properly, so it waits for the migration."),
    dict(id="lobby", icon="&#x1F6F9;", title="The Lobby", teaser=True, badge="BACK BURNER",
         desc="A little 3D lobby you can wander round: a skateboard parked by the door, a fogged-up window, and twelve hidden frames to find. Half sketched, waiting its turn."),
    dict(id="penrose-visuals", icon="&#x1F300;", title="PenrosePulse: looping visuals", teaser=True, badge="BACK BURNER",
         desc="Mirror-and-feedback pictures that loop forever, for the infinite staircase to climb through. An idea in the drawer."),
    dict(id="fm-replies", icon="&#x1F4FB;", title="Darklabs FM: replies", teaser=True, badge="BACK BURNER",
         desc="Saved feedback, replies, and a private inbox, once there's a proper server to keep them on. For now, feedback goes straight to a phone."),
    dict(id="shared-kit", icon="&#x2699;&#xFE0F;", title="One shared kit", teaser=True, badge="BACK BURNER",
         desc="Move every instrument onto the same audio and visual building blocks, so a fix in one place fixes them all."),
    dict(id="darklabs-caps", icon="&#x1F5DB;", title="DarkLabs, with a capital L", teaser=True, badge="BACK BURNER",
         desc="A visual-only respelling of the name. No links change, nothing breaks, it just looks sharper."),
    dict(id="earshot", icon="&#x1F442;", title="Earshot", teaser=True, badge="BACK BURNER",
         desc="A future audition tool for sorting and rating new material. Not live yet."),
    dict(id="crate-capture", icon="&#x1F4E6;", title="Crate Capture", teaser=True, badge="BACK BURNER",
         desc="A future tool for sourcing and tracking audio finds. Not live yet."),
]
