// Design Notes — practical sound-design technique reference, written for a sci-fi VR dash game.
// General, widely-taught game-audio/foley practice (not any one studio's proprietary work):
// layered construction, doppler for movement, sub for weight, restrained reverb for clarity in-engine.
export const NOTES = {
  blaster: ['Three layers, three jobs: a sub-ms noise click for the trigger snap, an FM "laser" body that\n    glides down in pitch (a falling pitch reads as energy leaving, not arriving), and a short high-passed\n    crack for distance. Keep the glide under 150 ms — longer reads as a cartoon, not a weapon.',
    'Classic arcade/sci-fi blasters (Star Wars blaster foley, most FPS energy weapons) are built from a\n    fast downward sweep + a resonant filter ping, almost never a straight tone — the pitch movement is\n    what sells "shot", the timbre sells "sci-fi".'],
  plasma: ['Plasma reads as unstable: modulate the filter cutoff with a slow LFO so the tone "boils" rather\n    than sitting static. Add a touch of sub so it has mass in a VR headset\'s sub-woofer channel, not just\n    a thin whine through the tiny drivers.'],
  zap: ['Electric zaps are noise-based, not tonal: band-pass noise with a fast random (jittered) amplitude\n    envelope reads as arcing electricity far better than a buzzy oscillator. Layer a low buzz underneath\n    only if the zap needs to feel dangerous rather than cosmetic (UI vs. hazard).'],
  explosion: ['Distance and size both live in the low end and the tail length, not the transient. For VR,\n    keep the crack short and forward but let the sub decay for 300–600 ms — that\'s what a chest-cavity\n    "thump" needs to feel big without becoming a wall of noise. Real foley explosions are almost always\n    multiple recordings layered: a crack, a body (often a slowed-down/pitched-down recording for extra\n    weight), and debris — the same "one job per layer" idea used in Layer Lab.'],
  whoosh: ['Whooshes are band-pass noise with a moving centre frequency — the *movement* of the filter is the\n    whole effect. For a dash/wall-run, sweep the filter up then down (an arc, not a straight ramp) so it\n    reads as passing *by* rather than just getting louder. Keep it short (300–500 ms) and dry: a wet,\n    reverberant whoosh reads as ambience, not motion.'],
  sweep: ['Risers/sweeps work by raising both pitch and filter cutoff together toward the payload moment —\n    that\'s the "anticipation" beat foley artists build before a hit or a teleport resolves. Don\'t over-use\n    reverb here either; the sense of speed comes from the sweep\'s slope, not from the room.'],
  mech: ['Mechanical sounds (servos, doors, docking clamps) are two sounds glued together: a continuous\n    "motor run" (a filtered saw or noise loop) and a hard "end-stop" transient when it reaches full travel.\n    Real foley for this is often a slowed-down drill, tape dispenser, or electric window motor, pitched\n    down for scale.'],
  pickup: ['Pickups and UI-positive stingers use a rising arpeggio (2–4 notes climbing) because ascending\n    pitch reads universally as "gain/reward" — descending reads as "loss". Keep the notes on a pleasant\n    scale (pentatonic is a common safe choice) so 100 pickups in a session never grates.'],
  ui: ['UI clicks should be almost all transient: under 80 ms, high-passed above ~1.5 kHz so they don\'t\n    compete with music or dialogue on a small speaker. In VR specifically, keep UI *dry* — reverb on UI\n    breaks the illusion that it\'s not part of the 3D world.'],
  loop: ['Ambient loops (grinding rails, engine hums, wind) need to disappear on repeat: vary the texture\n    with slow (0.5–3 Hz) filter or amplitude LFOs so the ear can\'t lock onto the loop point, and always\n    equal-power crossfade the seam (see Slice · Loop) — a level-only fade still leaves a phase click.'],
  impact: ['Impacts are almost entirely transient + a short body resonance. For sci-fi metal, add a few\n    inharmonic sine partials (not a clean harmonic series) after the hit — real metal doesn\'t ring in tune,\n    and that "wrongness" is what reads as futuristic rather than a cartoon frying pan.'],
  pistol: ['Game-industry pistol design is a stack, not one recording: (1) a mechanical click, (2) the\n    "crack" — the actual bang, mid-heavy and short, (3) body/weight in the low-mids, (4) sub for the chest\n    thump felt in VR haptics, (5) a casing "tink" a beat later, (6) a short slap-back tail that implies the\n    room without washing the shot out. Real recordings for game guns are frequently close-mic\'d blanks\n    layered with a separate distant "tail" mic — that\'s exactly the transient/tail split Pistol Lab exposes\n    as two independent layers.'],
  dash: ['Dash / blink abilities in movement-heavy games (wall-runs, grapples, teleport-dashes) are built\n    from three beats: a quick charge-up "whir" (rising pitch, under 150 ms, optional), the dash itself as a\n    doppler whoosh — pitch and volume both arc up then down as if something passed the player at speed —\n    and a soft landing thump so the motion has a full stop. Skip heavy reverb throughout; the speed reads\n    in the pitch/volume envelope shape, not the room.'],
  rail: ['This is "friction Foley": the classic technique for a scrape/grind is a filtered noise bed (a\n    sanding block, a shoe drag, a bowed metal rod in real Foley) rather than a synth tone — noise carries\n    the irregularity that makes friction sound physical. Excite a couple of resonant peaks tuned to an open\n    fifth or fourth apart and the grind starts to "sing" pleasantly instead of just hissing — that\'s the\n    technique behind pleasant-sounding rail/skate grinds in movement games.'],
};
NOTES.dash_whoosh = NOTES.dash; NOTES.dash_land = NOTES.dash;
NOTES.dash_whoosh = NOTES.dash; NOTES.dash_land = NOTES.dash;
export const GENERAL = ['One job per layer: never ask a single sound to be the transient, the body and the tail —\n  stack three short specialised sounds instead (Layer Lab is built around exactly this).',
  'A falling pitch reads as departure/impact; a rising pitch reads as arrival/reward — use the direction\n  on purpose, not by accident.',
  'Reverb is the easiest way to make a game SFX sound worse: real game engines add their own room via a\n  reverb zone or convolution bus, so a "dry-ish" source sound gives the sound designer the most control.\n  Sonic Smithy keeps every generated sound\'s room under ~35% mix for exactly this reason.',
  'Keep true peak at or below −1 dBTP with headroom for the platform\'s own limiter/normalisation, and\n  loudness-match a whole sound bank so no one sound is jarringly louder than its neighbours.'];

export function noteEl(h, kind) {
  const n = NOTES[kind] || [];
  if (!n.length) return null;
  return h('div', { class: 'guide' }, h('b', {}, '◆ design note'), n.map((t) => h('p', {}, t)));
}
